### ISSUE TITLE
[Feature] Use "offical" scrollable widget

### ISSUE THREAD

**Issue by dstansby** [brainglobe/cellfinder-napari#122]
In https://github.com/brainglobe/cellfinder-napari/pull/79 I added support for a scrollable widget, which was a bit hacky since it involved modifying private API in `magicgui`. My PR to do this properley in `magicgui` just got merged (https://github.com/napari/magicgui/issues/380), so when that finds its way into a `magicgui` release the currently way of implementing scrolling should be replaced with that.

**Comment by dstansby** [comment]
These are now a feature of magicgui (https://github.com/napari/magicgui/pull/388), but don't integrate with napari because of a bug :cry: (https://github.com/napari/magicgui/issues/431). so I think the action here is to get a fix merged to magicgui, which I'm currently proposing and discussing in https://github.com/napari/magicgui/pull/429

**Comment by adamltyson** [comment]
Finally added in #136. Thanks @dstansby!
