### ISSUE TITLE
[BUG] Package requirements

### ISSUE THREAD

**Issue by goanpeca** [brainglobe/cellfinder-napari#142]
**Describe the bug**
It seems the [setup.py](https://github.com/brainglobe/cellfinder-napari/blob/main/setup.py) file is not listing all the requirements that the package is explicitly using (importing)

**To Reproduce**
Search for the following packages in the codebase

```
    - imlib
    - magicgui
    - numpy
    - qtpy
    - skimage
    - tifffile
```

**Expected behaviour**
The package should list all the dependencies.

**Comment by adamltyson** [comment]
Thanks for spotting @goanpeca! Will fix now.

**Comment by goanpeca** [comment]
Hi @adamltyson thanks for the quick fix. Working on a pre-commit hook to help spot this more easily :) 

Cheers!
