### ISSUE TITLE
icon not making it into distribution

### ISSUE THREAD

**Issue by tlambert03** [brainglobe/cellfinder-napari#16]
The `.png` file in `resources` isn't getting packaged in the sdist, and so is missing in the [files on pypi](https://pypi.org/project/cellfinder-napari/#files).  You'll need to need to include them in your `MANIFEST.in` (see [here](https://github.com/napari/napari/blob/fbf24112c7dbec9b47d589205ff2c2cd6bffcb9d/MANIFEST.in#L4) for napari) and probably set `include_package_data = True` in your [setup.py](https://setuptools.readthedocs.io/en/latest/userguide/datafiles.html)

if you'd like something to check for these things, you can use [`check-manifest`](https://github.com/mgedmin/check-manifest)...  see example in napari's CI [here](https://github.com/napari/napari/blob/fbf24112c7dbec9b47d589205ff2c2cd6bffcb9d/.github/workflows/test_comprehensive.yml#L35-L50)

**Comment by adamltyson** [comment]
Added in 2e5decc4ec042bc98c01d69b116ce4b2604b10c3.

Thanks @tlambert03, `check-manifest` is really useful!
