### ISSUE TITLE
Training plugin not responsive. 

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/cellfinder-napari#27]
See [image.sc issue](https://forum.image.sc/t/napari-cellfinder-plugin-gui-unresponsive/57812/3). Looks like `cellfinder-core` is fine, and this an issue with the plugin specifically.

**Comment by ablot** [comment]
A fresh installed today seemed to work fine for me (windows computer).

**Comment by dstansby** [comment]
Given this is reported as fine now, I'm going to close. If this comes up again, feel free to re-open this issue, or open a new one (ideally with a small reproducible self-contained example).
