### ISSUE TITLE
Progress bar for cell detection

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/cellfinder-napari#38]
As part of improving user feedback in the GUI #12 , we should show updates on progress.

An initial improvement (also allowing to familiarise ourselves with making a progress bar) would be to display a progress bar during cell detection. Estimation of progress should be easy, as this is ~sequential through all planes in the image, so we can estimate from total number of planes, and number of planes processed.

This is already displayed in the logs/stdout so we can see how it's done there.

**Comment by alessandrofelder** [comment]
The [napari.utils.progress API docs](https://napari.org/api/stable/napari.utils.progress.html) look handy for this.
It's not immediately obvious to me whether it's possible to get the number of planes already progress from `cellfinder-core` into `cellfinder-napari` though 🤔

**Comment by dstansby** [comment]
I think the first step here is to add options in the relevant `cellfinder-core` functions/methods to make `tqdm` progress bars optional (ie. add `verbose` arguments that can be set to `False`), and also allow custom callbacks to be passed so we can use these to trigger a `napari` progress bar.
