### ISSUE TITLE
Modularise input parameters?

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/cellfinder-napari#41]
The many input parameters to our entry points (e.g. `detect.py`) make the code hard to read, and the parameters hard to validate.
Would we benefit from creating some "structs" (e.g. one each for classification, detection, training) that may even provide simple functionality (like `get_defaults` ?) that could be validated individually? (see also #37 ).

**Comment by alessandrofelder** [comment]
Possibly define [dataclasses](https://docs.python.org/3/library/dataclasses.html#dataclasses.asdict) for each of these "structs". These can be passed to the `cellfinder-core` via `fields()` or `asdict()`.

**Comment by paddyroddy** [comment]
are we reading any params via `argparse`?  Could do something like https://stackoverflow.com/a/37472037/7359333

**Comment by paddyroddy** [comment]
or a getter/setter pattern where we validate in the setter

**Comment by alessandrofelder** [comment]
Not going to touch the Curation Widget as part of this as it does not (to the same extent) suffer from passing lots of UI arguments around the various layers of code.
