### ISSUE TITLE
Provided trained models cause error in keras

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/cellfinder-napari#43]
Passing `resnet50_tv.h5` from [the gin-g server](https://gin.g-node.org/cellfinder/models) fails for me on Windows 10, in a conda env with
* Python 3.8.10
* napari==0.4.13
* cellfinder==0.4.19
* cellfinder-core==0.2.7
* -e git+https://github.com/brainglobe/cellfinder-napari@cb2f4f8062da9541b542459bb878a75028e85bd4#egg=cellfinder_napari
* keras==2.7.0

The error message suggests it's looking for a non-existent h5 attribute related to the model configuration? 
` ValueError: No model config found in the file at ...`

There's[ an initial clue that](https://github.com/keras-team/keras/issues/6937) this may be a Python 3.8-related issue, but haven't looked into it in-depth yet?

**Comment by adamltyson** [comment]
Does it work with 3.9? It [seems to work in CI](https://github.com/brainglobe/cellfinder-core/actions/runs/1757618485).

**Comment by alessandrofelder** [comment]
It seems detection is completed (only running it on planes 10-15 for debugging purposes):
> Detection complete - all planes done in 
> : 0:00:29.347457

Full error message:
> 2022-02-01 14:40:52.444882: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
> 2022-02-01 14:40:52.445553: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
> 2022-02-01 14:40:52.451176: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-6L5NNC1
> 2022-02-01 14:40:52.451850: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-6L5NNC1        
>      ----------------------------------------
> ValueErrorTraceback (most recent call last)
> c:\users\alessandro\anaconda3\envs\napari-env\lib\site-packages\superqt\utils\_qthreading.py in reraise(e=ValueError('No model config found in the file at D:\\brainglobe-data\\resnet50_tv.h5.'))      
>     610
>     611         def reraise(e):
> --> 612             raise e
>         e = ValueError('No model config 
> found in the file at D:\\brainglobe-data\\resnet50_tv.h5.')
>     613
>     614         worker.errored.connect(reraise)
> 
> c:\users\alessandro\anaconda3\envs\napari-env\lib\site-packages\superqt\utils\_qthreading.py in run(self=<napari._qt.qthreading.FunctionWorker object>)
>     175                 warnings.filterwarnings("always")
>     176                 warnings.showwarning = lambda *w: self.warned.emit(w)   
> --> 177                 result = self.work()
>         result = undefined
>         self.work = <bound method FunctionWorker.work of <napari._qt.qthreading.FunctionWorker object at 0x000001BEBDD51700>>
>     178             if isinstance(result, Exception):
>     179                 if isinstance(result, RuntimeError):
> 
> c:\users\alessandro\anaconda3\envs\napari-env\lib\site-packages\superqt\utils\_qthreading.py in work(self=<napari._qt.qthreading.FunctionWorker object>)        
>     350
>     351     def work(self) -> _R:       
> --> 352         return self._func(*self._args, **self._kwargs)
>         self._func = <function detect.<locals>.widget.<locals>.run at 0x000001BEBD642790>
>         self._args = (dask.array<stack, 
> shape=(100, 3992, 5680), dtype=uint16, chunksize=(1, 3992, 5680), chunktype=numpy.ndarray>, dask.array<stack, shape=(100, 3992, 5680), dtype=uint16, chunksize=(1, 3992, 5680), chunktype=numpy.ndarray>, (5.0, 2.0, 2.0), 16.0, 6.0, 15.0, 10, 
> 15, 0.6, 0.2, 10, 1.4, 100000, WindowsPath('D:/brainglobe-data/resnet50_tv.h5'), 2)
>         self._kwargs = {}
>     353
>     354
> 
> c:\users\alessandro\documents\ucl-projects\napari-plugins\cellfinder-napari\cellfinder_napari\detect.py in run(signal=dask.array<stack, shape=(100, 3992, 5680), dtype...unksize=(1, 3992, 5680), chunktype=numpy.ndarray>, background=dask.array<stack, shape=(100, 3992, 5680), dtype...unksize=(1, 3992, 5680), chunktype=numpy.ndarray>, voxel_sizes=(5.0, 2.0, 2.0), Soma_diameter=16.0, ball_xy_size=6.0, 
> ball_z_size=15.0, Start_plane=10, End_plane=15, Ball_overlap=0.6, Filter_width=0.2, Threshold=10, Cell_spread=1.4, Max_cluster=100000, Trained_model=WindowsPath('D:/brainglobe-data/resnet50_tv.h5'), Number_of_free_cpus=2)
>     247         ):
>     248
> --> 249             points = cellfinder_run(
>         points = undefined
>         global cellfinder_run = undefined
>         signal = dask.array<stack, shape=(100, 3992, 5680), dtype=uint16, chunksize=(1, 3992, 5680), chunktype=numpy.ndarray>
>         background = dask.array<stack, shape=(100, 3992, 5680), dtype=uint16, chunksize=(1, 3992, 5680), chunktype=numpy.ndarray>
>         voxel_sizes = (5.0, 2.0, 2.0)   
>         global soma_diameter = undefined
>         Soma_diameter = 16.0
>         ball_xy_size = 6.0
>         ball_z_size = 15.0
>         global start_plane = undefined  
>         Start_plane = 10
>         global end_plane = undefined    
>         End_plane = 15
>         global ball_overlap_fraction = undefined
>         Ball_overlap = 0.6
>         global log_sigma_size = undefined
>         Filter_width = 0.2
>         global n_sds_above_mean_thresh = undefined
>         Threshold = 10
>         global soma_spread_factor = undefined
>         Cell_spread = 1.4
>         global max_cluster_size = undefined
>         Max_cluster = 100000
>         global trained_model = undefined
>         Trained_model = WindowsPath('D:/brainglobe-data/resnet50_tv.h5')        
>         global n_free_cpus = undefined  
>         Number_of_free_cpus = 2
>     250                 signal,
>     251                 background,     
> 
> c:\users\alessandro\anaconda3\envs\napari-env\lib\site-packages\cellfinder_core\main.py in main(signal_array=dask.array<stack, shape=(100, 3992, 5680), dtype...unksize=(1, 3992, 5680), chunktype=numpy.ndarray>, background_array=dask.array<stack, shape=(100, 3992, 5680), dtype...unksize=(1, 3992, 5680), chunktype=numpy.ndarray>, voxel_sizes=(5.0, 2.0, 2.0), start_plane=10, end_plane=15, trained_model=WindowsPath('D:/brainglobe-data/resnet50_tv.h5'), model_weights=None, model='resnet50_tv', batch_size=32, n_free_cpus=2, network_voxel_sizes=[5, 1, 1], soma_diameter=16.0, ball_xy_size=6.0, ball_z_size=15.0, ball_overlap_fraction=0.6, log_sigma_size=0.2, n_sds_above_mean_thresh=10, soma_spread_factor=1.4, max_cluster_size=100000, cube_width=50, cube_height=50, cube_depth=20, network_depth='50')
>      70     if len(points) > 0:
>      71         logging.info("Running classification")
> ---> 72         points = classify.main( 
>         points = [<class 'imlib.cells.cells.Cell'>, ([3278, 270, 11], 1), <class 'imlib.cells.cells.Cell'>, ([3276, 271, 11], 1), <class 'imlib.cells.cells.Cell'>, ([3263, 273, 12], 1), <class 'imlib.cells.cells.Cell'>, ([3198, 282, 12], 1), <class 'imlib.cells.cells.Cell'>, ([3218, 280, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2407, 313, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2063, 337, 12], 1), <class 'imlib.cells.cells.Cell'>, ([3765, 350, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2976, 369, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2947, 376, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2968, 372, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2962, 374, 11], 1), <class 'imlib.cells.cells.Cell'>, ([3878, 379, 12], 1), <class 'imlib.cells.cells.Cell'>, ([3885, 382, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2937, 390, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2709, 391, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2924, 399, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2720, 400, 12], 1), <class 'imlib.cells.cells.Cell'>, ([3957, 404, 11], 1), <class 'imlib.cells.cells.Cell'>, ([2904, 414, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2890, 425, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2880, 433, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2877, 436, 11], 1), <class 'imlib.cells.cells.Cell'>, ([2874, 439, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2864, 449, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2855, 462, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2795, 478, 12], 1), <class 'imlib.cells.cells.Cell'>, ([4239, 515, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2819, 516, 11], 1), <class 'imlib.cells.cells.Cell'>, ([4248, 517, 11], 1), <class 'imlib.cells.cells.Cell'>, ([2814, 542, 12], 1), <class 'imlib.cells.cells.Cell'>, ([4490, 622, 11], 1), <class 'imlib.cells.cells.Cell'>, ([1160, 652, 12], 1), <class 'imlib.cells.cells.Cell'>, ([1170, 660, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2811, 662, 12], 1), <class 'imlib.cells.cells.Cell'>, ([1184, 674, 12], 1), <class 'imlib.cells.cells.Cell'>, ([1109, 675, 12], 1), <class 'imlib.cells.cells.Cell'>, ([1124, 682, 12], 1), <class 'imlib.cells.cells.Cell'>, ([1152, 675, 12], 1), <class 'imlib.cells.cells.Cell'>, ([1175, 679, 11], 1), <class 'imlib.cells.cells.Cell'>, ([1190, 680, 12], 1), <class 'imlib.cells.cells.Cell'>, ([723, 814, 
> 12], 1), <class 'imlib.cells.cells.Cell'>, ([4023, 849, 11], 1), <class 'imlib.cells.cells.Cell'>, ([2283, 894, 12], 1), <class 'imlib.cells.cells.Cell'>, ([4885, 910, 11], 1), <class 'imlib.cells.cells.Cell'>, ([2818, 976, 12], 1), <class 
> 'imlib.cells.cells.Cell'>, ([2642, 1027, 12], 1), <class 'imlib.cells.cells.Cell'>, ([4523, 1044, 11], 1), <class 'imlib.cells.cells.Cell'>, ([689, 1077, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2811, 1089, 11], 1), <class 'imlib.cells.cells.Cell'>, ([3589, 1106, 11], 1), <class 'imlib.cells.cells.Cell'>, ([2037, 1191, 11], 1), <class 'imlib.cells.cells.Cell'>, ([2148, 1194, 12], 1), <class 'imlib.cells.cells.Cell'>, ([3573, 1197, 12], 1), <class 'imlib.cells.cells.Cell'>, ([3652, 1219, 12], 1), <class 'imlib.cells.cells.Cell'>, ([1994, 1227, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2658, 1228, 11], 1), <class 'imlib.cells.cells.Cell'>, ([2656, 1271, 12], 1), <class 'imlib.cells.cells.Cell'>, ([540, 1302, 12], 1), <class 'imlib.cells.cells.Cell'>, ([529, 1315, 12], 1), <class 'imlib.cells.cells.Cell'>, ([3130, 1339, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2847, 1416, 12], 1), <class 'imlib.cells.cells.Cell'>, ([424, 1526, 12], 1), <class 'imlib.cells.cells.Cell'>, ([425, 1567, 12], 1), <class 'imlib.cells.cells.Cell'>, ([680, 1571, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2218, 1575, 11], 1), <class 'imlib.cells.cells.Cell'>, ([2896, 1624, 12], 1), <class 'imlib.cells.cells.Cell'>, ([4593, 1658, 11], 1), <class 'imlib.cells.cells.Cell'>, ([2341, 1661, 11], 1), <class 'imlib.cells.cells.Cell'>, ([2856, 1912, 11], 1), <class 'imlib.cells.cells.Cell'>, ([5299, 2292, 12], 1), <class 'imlib.cells.cells.Cell'>, ([5255, 2388, 12], 1), <class 'imlib.cells.cells.Cell'>, ([344, 2390, 11], 1), <class 'imlib.cells.cells.Cell'>, ([5246, 2393, 11], 1), <class 'imlib.cells.cells.Cell'>, ([5240, 2404, 11], 1), <class 'imlib.cells.cells.Cell'>, ([5146, 2506, 12], 1), <class 'imlib.cells.cells.Cell'>, ([5154, 2503, 12], 1), <class 
> 'imlib.cells.cells.Cell'>, ([5137, 2516, 12], 1), <class 'imlib.cells.cells.Cell'>, ([5148, 2559, 12], 1), <class 'imlib.cells.cells.Cell'>, ([5137, 2580, 12], 
> 1), <class 'imlib.cells.cells.Cell'>, ([604, 2902, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2918, 3335, 11], 1), <class 'imlib.cells.cells.Cell'>, ([2918, 3343, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2178, 3345, 11], 1), <class 'imlib.cells.cells.Cell'>, ([2918, 3351, 12], 1), <class 'imlib.cells.cells.Cell'>, ([3243, 3492, 12], 1), <class 'imlib.cells.cells.Cell'>, ([4499, 3501, 11], 1), <class 'imlib.cells.cells.Cell'>, ([4492, 3504, 12], 1), <class 'imlib.cells.cells.Cell'>, ([3232, 3563, 12], 1), <class 'imlib.cells.cells.Cell'>, ([3258, 3574, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2594, 3591, 12], 1), <class 'imlib.cells.cells.Cell'>, ([1275, 3683, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2419, 318, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2702, 386, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2790, 471, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2791, 472, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2834, 490, 13], 1), <class 'imlib.cells.cells.Cell'>, ([3662, 1341, 13], 1), <class 'imlib.cells.cells.Cell'>, ([3153, 1344, 13], 1), <class 'imlib.cells.cells.Cell'>, ([4842, 2560, 13], 1), <class 'imlib.cells.cells.Cell'>, ([461, 2746, 13], 1), <class 'imlib.cells.cells.Cell'>, ([3001, 3399, 13], 1), <class 'imlib.cells.cells.Cell'>, ([3343, 3635, 13], 1), <class 'imlib.cells.cells.Cell'>, ([2996, 363, 13], 
> 1), <class 'imlib.cells.cells.Cell'>, ([2990, 366, 13], 1), <class 'imlib.cells.cells.Cell'>, ([137, 2911, 13], 1)]     
>         classify.main = <function main at 0x000001BEBDD6BA60>
>         signal_array = dask.array<stack, shape=(100, 3992, 5680), dtype=uint16, 
> chunksize=(1, 3992, 5680), chunktype=numpy.ndarray>
>         background_array = dask.array<stack, shape=(100, 3992, 5680), dtype=uint16, chunksize=(1, 3992, 5680), chunktype=numpy.ndarray>
>         n_free_cpus = 2
>         voxel_sizes = (5.0, 2.0, 2.0)   
>         network_voxel_sizes = [5, 1, 1] 
>         batch_size = 32
>         cube_height = 50
>         cube_width = 50
>         cube_depth = 20
>         trained_model = WindowsPath('D:/brainglobe-data/resnet50_tv.h5')        
>         model_weights = None
>         network_depth = '50'
>      73             points,
>      74             signal_array,       
> 
> c:\users\alessandro\anaconda3\envs\napari-env\lib\site-packages\cellfinder_core\classify\classify.py in main(points=[<class 'imlib.cells.cells.Cell'>, ([3278, 270, 11], 1), <class 'imlib.cells.cells.Cell'>, ([3276, 271, 11], 1), <class 'imlib.cells.cells.Cell'>, ([3263, 273, 12], 1), <class 'imlib.cells.cells.Cell'>, ([3198, 282, 12], 1), <class 'imlib.cells.cells.Cell'>, ([3218, 280, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2407, 313, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2063, 337, 12], 1), <class 'imlib.cells.cells.Cell'>, ([3765, 350, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2976, 369, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2947, 376, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2968, 372, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2962, 374, 11], 1), <class 'imlib.cells.cells.Cell'>, ([3878, 379, 12], 1), <class 'imlib.cells.cells.Cell'>, ([3885, 382, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2937, 390, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2709, 391, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2924, 399, 12], 1), <class 'imlib.cells.cells.Cell'>, ([2720, 400, 12], 1), <class 'imlib.cells.cells.Cell'>, ([3957, 404, 11], 1), <class 'imlib.cells.cells.Cell'>, ([2904, 414, 12], 1), ...], signal_array=dask.array<stack, shape=(100, 3992, 5680), dtype...unksize=(1, 3992, 5680), chunktype=numpy.ndarray>, background_array=dask.array<stack, shape=(100, 3992, 5680), dtype...unksize=(1, 3992, 5680), chunktype=numpy.ndarray>, n_free_cpus=2, voxel_sizes=(5.0, 2.0, 2.0), network_voxel_sizes=[5, 1, 1], batch_size=32, cube_height=50, cube_width=50, cube_depth=20, trained_model=WindowsPath('D:/brainglobe-data/resnet50_tv.h5'), model_weights=None, network_depth='50', max_workers=3)
>      49     )
>      50
> ---> 51     model = get_model(
>         model = undefined
>         global get_model = <function get_model at 0x000001BEBDD6BAF0>
>         global existing_model = undefined
>         trained_model = WindowsPath('D:/brainglobe-data/resnet50_tv.h5')        
>         model_weights = None
>         network_depth = '50'
>         global models = {'18': '18-layer', '34': '34-layer', '50': '50-layer', '101': '101-layer', '152': '152-layer'}  
>         global inference = undefined    
>      52         existing_model=trained_model,
>      53         model_weights=model_weights,
> 
> c:\users\alessandro\anaconda3\envs\napari-env\lib\site-packages\cellfinder_core\classify\tools.py in get_model(existing_model=WindowsPath('D:/brainglobe-data/resnet50_tv.h5'), model_weights=None, network_depth='50-layer', learning_rate=0.0001, inference=True, continue_training=False)
>      33     if existing_model is not None:
>      34         logging.debug(f"Loading 
> model: {existing_model}")
> ---> 35         return tf.keras.models.load_model(existing_model)
>         global tf.keras.models.load_model = <function load_model at 0x000001BF22CFBDC0>
>         existing_model = WindowsPath('D:/brainglobe-data/resnet50_tv.h5')       
>      36     else:
>      37         logging.debug(f"Creating a new instance of model: {network_depth}")
> 
> c:\users\alessandro\anaconda3\envs\napari-env\lib\site-packages\keras\utils\traceback_utils.py in error_handler(*args=(WindowsPath('D:/brainglobe-data/resnet50_tv.h5'),), **kwargs={})
>      65     except Exception as e:  # pylint: disable=broad-except
>      66       filtered_tb = _process_traceback_frames(e.__traceback__)
> ---> 67       raise e.with_traceback(filtered_tb) from None
>         e.with_traceback = undefined    
>         filtered_tb = undefined
>      68     finally:
>      69       del filtered_tb
> 
> c:\users\alessandro\anaconda3\envs\napari-env\lib\site-packages\keras\saving\hdf5_format.py in load_model_from_hdf5(filepath=WindowsPath('D:/brainglobe-data/resnet50_tv.h5'), custom_objects={}, compile=True)
>     175     model_config = f.attrs.get('model_config')
>     176     if model_config is None:    
> --> 177       raise ValueError(f'No model config found in the file at {filepath}.')
>         global ValueError = undefined
>     178     if hasattr(model_config, 'decode'):
>     179       model_config = model_config.decode('utf-8')
> 
> ValueError: No model config found in the file at D:\brainglobe-data\resnet50_tv.h5.

Just to exclude all possibilities: Is this because my laptop does not have an NVIDIA GPU (and hence no CUDA), @adamltyson ?

I will try on a clean conda env with Python 3.9 now

**Comment by adamltyson** [comment]
> Just to exclude all possibilities: Is this because my laptop does not have an NVIDIA GPU (and hence no CUDA)?

Nah, it runs on CPU fine.

I think the problem is because you're passing a model weights file as a model. `cellfinder-core` accepts either:
* Full model file  (i.e. architecture and weights).
* Model specification (as resnet depth) and model weights.

The file you downloaded is just the weights for a 3D ResNet-50 which are downloaded by default into `~.cellfinder/model_weights`. Only weights are supplied by default, because the model files are very large.

The napari plugin (for now) only supports:
* Using the supplied pre-trained weights
* Supplying a trained model

This was originally for simplicity, otherwise the training widget would have more options, and so would the detection widget.

I think if you leave the model entry blank (or default, not sure what's there), it should run ok using the pre-trained weights.
