### ISSUE TITLE
Do we want testing CI to only be ran after linting?

### ISSUE THREAD

**Issue by paddyroddy** [brainglobe/cellfinder-napari#63]
Here https://github.com/brainglobe/cellfinder-core/pull/29#discussion_r810246314 and here https://github.com/brainglobe/cellfinder/pull/192#discussion_r810249127 @adamltyson asked if we could run tests only after linting passes, do you want that here?

Also what would happen about the plugin CI?

**Comment by adamltyson** [comment]
> Also what would happen about the plugin CI?

not sure what you mean here

**Comment by paddyroddy** [comment]
> > Also what would happen about the plugin CI?
> 
> not sure what you mean here

Sorry I meant that do we want the plugin CI to run regardless of linting?

**Comment by adamltyson** [comment]
I think I don't have very strong feelings on this. The only thing we should enforce is that the deployment doesn't run unless the tests pass (obvs). Happy to go with any consensus (@alessandrofelder?).
