### ISSUE TITLE
Run tests on Python 3.9

### ISSUE THREAD

**Issue by dstansby** [brainglobe/cellfinder-napari#83]
Since Python 3.8 is getting a bit old now, we should run tests on Python 3.9, and possibly Pytohn 3.10?

**Comment by adamltyson** [comment]
I think so. Perhaps (semi) formally adopting [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html)?

**Comment by alessandrofelder** [comment]
My only worry about moving to 3.9 is that Napari currently still seems to support Python 3.8 (as well as 3.9, and 3.10) - I don't know how many users run on 3.8... should we run tests on 3.8 and on 3.10 (and trust that means it will work for 3.9 too)?

**Comment by alessandrofelder** [comment]
Yep, sorry, I misunderstood :) fine by me!
