### ISSUE TITLE
`Pre-commit` checks seem to be incompatible with the `bump2version` config

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/cellfinder-napari#84]
See https://github.com/brainglobe/cellfinder-napari/actions/runs/1999306323

Also, do we need linting checks in their own workflow, as well as in the main `test_and_deploy` workflow?

**Comment by paddyroddy** [comment]
I think someone has done a merge and accidentally reintroduced the `linting_checks.yml` file https://github.com/brainglobe/cellfinder-napari/blob/main/.github/workflows/linting_checks.yml that shouldn't be there
