### ISSUE TITLE
Cannot load cellfinder output directory to visualise results

### ISSUE THREAD

**Issue by chrytsi** [brainglobe/cellfinder-napari#87]
Hello,

I am not able to visualise cellfinder results because I cannot load cellfinder output directories. 
I can load images just fine, when I drag and drop a cellfinder output directory containing an xml file, however, I get the following error:  `Could not find a backend to open path/to/directory`

I get this error in `cellfinder-napari==0.0.19rc0` and in `cellfinder-napari==0.0.19`

My conda environment has Python 3.7 on a Windows 7 machine.

**Comment by adamltyson** [comment]
Could you try updating napari (`pip install napari -U`) and also update the reader plugin (`pip install brainglobe-napari-io -U`)?

At this point though, it might be worth creating a new conda env with Python 3.9 and re-installing cellfinder (sorry, i know everything changes each time you come back to the software!).

**Comment by chrytsi** [comment]
Hi, thanks for getting back to me so quickly!
I knew my Windows 7 was going to become an issue sooner or later - unfortunately I cannot install python 3.9 on this Windows 7 machine (waiting for a new Windows 10 one...).

I was able to update both napari and the reader plugin in my 3.7 environment but whe I try to load a cellfiner output directory I get this error:
`ValueError: There is no registered plugin named 'brainglobe-napari-io'. Names of plugins offering readers are: {'builtins', 'ndtiffs'}`

**Comment by chrytsi** [comment]
Surprisingly I was able to load an xml file by dragging and dropping the xml file itself instead of the output directory. :)

**Comment by adamltyson** [comment]
Hmm, both should work. A fresh environment (3.8 if that works), should hopefully sort it.
