### ISSUE TITLE
Thumbs.db prevents loading image directory in napari

### ISSUE THREAD

**Issue by chrytsi** [brainglobe/cellfinder-napari#88]
Hello,

I have trouble loading some serial2p image directories in napari on a Windows 7 Machine because of a hidden Thumbs.db file in the image directory.
When I drag and drop the direcotry into napari I receive the following error:
`ValueError: Could not find a backend to open 'path/to/images/Thumbs.db' with iomode 'ri'.`

Any suggestions on how to get around this?

Cheers!

**Comment by adamltyson** [comment]
In this case it's not a BrainGlobe plugin being used to the load the image data, so there's not much we can do. Can you delete the file?

**Comment by chrytsi** [comment]
Initially I wasn't. Found a way to delete it, however. 
Thank you!

In case anyone else has issues deleting them:
https://answers.microsoft.com/en-us/windows/forum/all/unable-to-delete-thumbsdb/476dbfa7-6cd8-43a7-b162-c9228edd3049
